package com.capg.springboot.entity;

import com.capg.springboot.enums.ApplicationStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

// This class maps to the "applications" table in the database
// One row = one job application by one seeker for one job

@Entity
@Table(
    name = "applications",
    uniqueConstraints = @UniqueConstraint(
        columnNames = {"user_id", "job_id"},  // same seeker cannot apply to same job twice
        name = "uk_user_job"
    )
)
@Getter
@Setter
public class Application {

    // Primary key - auto generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ID of the job seeker who applied
    // This is NOT a JPA foreign key because users are in a different database
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // ID of the job they applied for
    // This is NOT a JPA foreign key because jobs are in a different database
    @Column(name = "job_id", nullable = false)
    private Long jobId;

    // Path to the resume file they uploaded
    @Column(name = "resume_url", nullable = false, columnDefinition = "TEXT")
    private String resumeUrl;

    // Optional message from the seeker to the recruiter
    @Column(name = "cover_letter", columnDefinition = "TEXT")
    private String coverLetter;

    // Current status of this application
    // @Enumerated(STRING) stores "APPLIED" in the DB, not 0, 1, 2
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ApplicationStatus status = ApplicationStatus.APPLIED;

    // Private note by the recruiter - seeker CANNOT see this
    @Column(name = "recruiter_note", columnDefinition = "TEXT")
    private String recruiterNote;

    // Set automatically when first saved - never changes after that
    @CreationTimestamp
    @Column(name = "applied_at", updatable = false)
    private LocalDateTime appliedAt;

    // Set automatically every time record is updated
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

}
