server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "@Kussu321"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
        max-file-size: 10MB
        max-request-size: 11MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: jobportal_super_secret_key_must_be_at_least_32_characters_long  
  access-expiry-ms: 9000000
  refresh-expiry-ms: 604800000

cloudinary:
  cloud-name: drp2tntul
  api-key: 488716938256727
  api-secret: IsHJpXYjAZJTAoBlyURzC_H7nFU

management:
  endpoints:
    web:
      exposure:
        include: health, info