server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

eureka:
  client:
    register-with-eureka: false   # server does not register itself
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false   # set true in production

management:
  endpoints:
    web:
      exposure:
        include: health,info
